name: pandovie
description: Application for save movie.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^7.8.1
  auto_route_generator: ^7.3.1
  cached_network_image: ^3.2.1
  collection: ^1.16.0
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  injectable: ^2.3.0
  injectable_generator: ^2.4.0
  flutter_screenutil: ^5.9.0
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.8
  dio: ^5.3.2
  freezed: ^2.3.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_hooks: ^0.20.3
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.14
  path_provider: ^2.1.0
  flutter_image_compress: ^2.0.4
  http: ^1.1.0
  lottie: ^2.6.0
  syncfusion_flutter_charts: ^22.2.11
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  flutter_zoom_drawer: ^3.1.1
  flutter_animate: ^4.2.0+1
  palette_generator: ^0.3.3+3
  intl: ^0.18.1
  ensure_initialized: ^0.1.0
  uuid: ^4.1.0
  assorted_layout_widgets: ^8.0.5
  slide_to_act: ^2.0.2
  overlay_widget: ^1.0.4

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/fonts/

  fonts:
  - family: InriaSerif
    fonts:
      - asset: assets/fonts/InriaSerif-Regular.ttf