name: Build Apk

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:

  mobile_ci:
    runs-on: windows-latest
    environment: D_NAME

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-java@v1.3.0
      with:
          java-version: '12.x'
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Generating release keystore and SHA1 key
      shell: powershell
      run: |
          keytool -genkey -v -dname "${{ secrets.D_NAME }}" -keystore D:\a\Pandovie\Pandovie\android\upload-keystore.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -storepass '${{ secrets.STOREPASS }}' -alias '${{ secrets.ALIAS }}' -keypass '${{ secrets.KEYPASS }}'
    
    - name: Create key.properties
      shell: powershell
      run: New-Item -path D:\a\Pandovie\Pandovie\android\ -type file -name "key.properties"

    - name: Set key.properties content
      shell: powershell
      run: Set-Content D:\a\Pandovie\Pandovie\android\key.properties '${{ secrets.KEY_PROPERTIES }}'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Restore the main dependencies
      run: flutter pub get

    - name: Build Android APK
      run: flutter build apk --obfuscate --split-debug-info=build/debug_info --release

    - name: Build Android AAB
      run: flutter build appbundle --obfuscate --split-debug-info=build/debug_info
