name: Build first aab Windows

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:

  pre_build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-java@v1.3.0
      with:
          java-version: '12.x'
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Generating release keystore and SHA1 key
      shell: powershell
      run: |
          keytool -genkey -v -dname "${{ secrets.D_NAME }}" -keystore D:\a\mobile_ci\mobile_ci\android\upload-keystore.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -storepass '${{ secrets.STOREPASS }}' -alias '${{ secrets.ALIAS }}' -keypass '${{ secrets.KEYPASS }}'
    
    - name: Create key.properties
      shell: powershell
      run: New-Item -path D:\a\mobile_ci\mobile_ci\android\ -type file -name "key.properties"

    - name: Set key.properties content
      shell: powershell
      run: Set-Content D:\a\mobile_ci\mobile_ci\android\key.properties '${{ secrets.KEY_PROPERTIES }}'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Restore the main dependencies
      run: flutter pub get

    - name: Build Android APK
      run: flutter build apk --obfuscate --split-debug-info=build/debug_info --release --build-number "${{ secrets.CODE_VERSION }}" --build-name="${{ secrets.APP_VERSION }}"

    - name: Build Android AAB
      run: flutter build appbundle --obfuscate --split-debug-info=build/debug_info --build-number "${{ secrets.CODE_VERSION }}" --build-name="${{ secrets.APP_VERSION }}"

    - name: Upload aab file
      uses: actions/upload-artifact@v3
      with:
        name: abb-file
        path: D:\a\mobile_ci\mobile_ci\build\app\outputs\bundle\release\app-release.aab

    - name: Upload mapping file
      uses: actions/upload-artifact@v3
      with:
        name: mapping-file
        path: D:\a\mobile_ci\mobile_ci\build\app\outputs\mapping\release\mapping.txt

    - name: Upload apk file
      uses: actions/upload-artifact@v3
      with:
        name: apk-file
        path: D:\a\mobile_ci\mobile_ci\build\app\outputs\flutter-apk\app-release.apk
  
    - name: Upload jks file
      uses: actions/upload-artifact@v3
      with:
        name: jks-file
        path: D:\a\mobile_ci\mobile_ci\android\upload-keystore.jks

    - name: Upload key.properties file
      uses: actions/upload-artifact@v3
      with:
        name: key-file
        path: D:\a\mobile_ci\mobile_ci\android\key.properties

    - name: Clean up flutter
      if: ${{ always() }}
      run: flutter clean
  
  release:
    name: create_release
    needs: [ pre_build ]
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
  
    - name: Download aab file
      uses: actions/download-artifact@v3
      with:
        name: abb-file

    - name: Download mapping file
      uses: actions/download-artifact@v3
      with:
        name: mapping-file

    - name: Download apk file
      uses: actions/download-artifact@v3
      with:
        name: apk-file

    - name: Download key.properties file
      uses: actions/download-artifact@v3
      with:
        name: key-file

    - name: Download jks file
      uses: actions/download-artifact@v3
      with:
        name: jks-file
        
    - name: Create GitHub release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/Users/runner/work/mobile_ci/mobile_ci/key.properties,/Users/runner/work/mobile_ci/mobile_ci/upload-keystore.jks,/Users/runner/work/mobile_ci/mobile_ci/app-release.apk,/Users/runner/work/mobile_ci/mobile_ci/mapping.txt,/Users/runner/work/mobile_ci/mobile_ci/app-release.aab"
        name: "${{ secrets.APP_VERSION }}"
        tag: "${{ secrets.APP_VERSION }}"

    # /home/runner/work/mobile_ci/mobile_ci/app-release.apk
  
    # - name: Upload Android app to Google Play
    #   uses: r0adkll/upload-google-play@v1.1.1
    #   with:
    #     serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
    #     packageName: ${{ secrets.ANDROID_PACKAGE_ID }}
    #     releaseFiles: D:\a\mobile_ci\mobile_ci\build\app\outputs\bundle\release\app-release.aab
    #     mappingFile: D:\a\mobile_ci\mobile_ci\build\app\outputs\mapping\release\mapping.txt
    #     track: alpha
    #     status: draft
